import os

SLACK_BOT_TOKEN = os.getenv("SLACK_BOT_TOKEN")
SLACK_SIGNING_SECRET = os.getenv("SLACK_SIGNING_SECRET")
DATABASE_URL = os.getenv("DATABASE_URL")
TIMEZONE = os.getenv("TIMEZONE", "America/New_York")
SYSTEM_ISSUES_CHANNEL = "C08JTKR1RPT"
SLACK_CHANNEL_ID = SYSTEM_ISSUES_CHANNEL