CREATE TABLE tickets (
    ticket_id SERIAL PRIMARY KEY,
    issue_type VARCHAR(255) NOT NULL,
    priority VARCHAR(50) NOT NULL,
    assigned_to VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
